<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "spt_newscalender"
 *
 * Auto generated by Extension Builder 2017-05-26
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'News Calender',
    'description' => 'Extension to display news/event articles in jquery responsive calender view',
    'category' => 'plugin',
    'author' => 'Merin Annie Vincent',
    'author_email' => 'merin@spawoz.com',
    'company' => 'Spawoz Technologies Pvt Ltd.',
    'state' => 'stable',
    'internal' => '',
    'uploadfolder' => '0',
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '1.0.0',
    'constraints' => [
        'depends' => [
            'typo3' => '7.6.0-8.7.99',
            'news'  => '6.0.0',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
