<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "spt_typo3audit"
 *
 * Auto generated by Extension Builder 2019-09-25
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'TYPO3 Audit',
    'description' => 'Extension for TYPO3 website audit',
    'category' => 'module',
    'module' => '',
    'author' => 'Arun Chandran',
    'author_email' => 'arun@spawoz.com',
    'state' => 'stable',
    'uploadfolder' => 0,
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '1.0.0',
    'constraints' => [
        'depends' => [
            'typo3' => '8.7.0-9.5.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
